"""Added role and registered on field for the user, added __init__ function to autogenerate a few fields

Revision ID: 0c32be94e2eb
Revises: 4df2680d70f8
Create Date: 2020-05-25 00:15:59.854474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c32be94e2eb'
down_revision = '4df2680d70f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###
