"""nothing changed

Revision ID: 134e1f242a7a
Revises: 9abba916a668
Create Date: 2020-05-24 22:33:58.909068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134e1f242a7a'
down_revision = '9abba916a668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
