"""Name column on Profile model is now nullable. Adding support for auto creation of profile during creation of account without details

Revision ID: 4df2680d70f8
Revises: a4cb2544b983
Create Date: 2020-05-24 22:50:55.706618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df2680d70f8'
down_revision = 'a4cb2544b983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
