"""nothing changed

Revision ID: 6b9de48d441e
Revises: 134e1f242a7a
Create Date: 2020-05-24 22:35:10.493020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9de48d441e'
down_revision = '134e1f242a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
