"""nothing changed

Revision ID: a4cb2544b983
Revises: 6b9de48d441e
Create Date: 2020-05-24 22:37:58.870489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cb2544b983'
down_revision = '6b9de48d441e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
